### PR TITLE
Add new Guest user image

### LINKED ISSUE #31: the user login image is not proper
Screenshot 2019-10-20 at 4 55 19 PM

### PR DESCRIPTION
**Pull request by parammittal16**
Fixes #31 @TdevM @himankbhalla   plz review sir

### CODE REVIEW

**Comment by sarthak-1998** [comment]
@himankbhalla and @TdevM can you check ?

**Comment by parammittal16** [comment]
@himankbhalla @TdevM @sarthak-1998 any updates here ??

**Comment by TdevM** [comment]
@parammittal16 Will merge it soon, thanks for your contribution.

**Comment by parammittal16** [comment]
@TdevM thanks for the reply. I hope this will get merged asap within this week. So that I can proceed further to fill the swag form before it expires.

**Comment by parammittal16** [comment]
THANKS ;)

**Pull request merged**
